# Generated by Django 3.2.12 on 2022-04-02 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20220402_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='balance',
            field=models.FloatField(default=0.0, verbose_name='Balance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.FloatField(verbose_name='Montant initial'),
        ),
    ]
