# Generated by Django 3.2.12 on 2022-04-03 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_alter_vehicle_vehicle_status'),
        ('budget', '0004_auto_20220403_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant initial'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Balance'),
        ),
        migrations.CreateModel(
            name='Acquittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(default=None, verbose_name='Numéro de décharge')),
                ('beneficiary', models.CharField(default='', max_length=200, verbose_name='Bénéficiaire')),
                ('allocation', models.IntegerField(choices=[(1000, 'basique: 1000 DH'), (1500, 'extra: 1500 DH')], default=1000, max_length=1, verbose_name='Affectation')),
                ('assignedAt', models.DateField(default=None)),
                ('log_number', models.IntegerField(default=None, verbose_name='Numéro de carnet de bord')),
                ('amount', models.DecimalField(decimal_places=2, default=1000.0, max_digits=7, verbose_name='Montant')),
                ('observation', models.TextField(blank=True, default='', verbose_name='Observation')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.budget')),
                ('vehicle', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Décharge',
                'verbose_name_plural': 'Décharges',
                'ordering': ('-createdAt',),
            },
        ),
    ]
