# Generated by Django 3.2.12 on 2022-04-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20220403_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquittance',
            name='assignedAt',
            field=models.DateField(default=None, verbose_name="Date d'attribution"),
        ),
    ]
