# Generated by Django 3.2.12 on 2022-04-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_acquittance_assignedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquittance',
            name='allocation',
            field=models.IntegerField(choices=[(1000, 'basique: 1000 DH'), (1500, 'extra: 1500 DH')], default=1000, verbose_name='Affectation'),
        ),
    ]
