# Generated by Django 3.2.12 on 2022-05-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_acquittance_allocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acquittance',
        ),
    ]
