# Generated by Django 3.2.12 on 2022-04-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0008_mission_return_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='return_time',
            field=models.DateTimeField(blank=True, verbose_name='Heure retour'),
        ),
    ]
