# Generated by Django 3.2.12 on 2022-04-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry', models.CharField(blank=True, default="Ministère de l'intérieur", max_length=50, verbose_name='Ministère de tutelle')),
                ('province', models.CharField(blank=True, default='', max_length=50, verbose_name='Province')),
                ('department', models.CharField(blank=True, default='', max_length=70, verbose_name='Département')),
                ('service', models.CharField(blank=True, default='', max_length=50, verbose_name='Service')),
                ('telephone', models.CharField(blank=True, default='', max_length=15, verbose_name='Téléphone')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='Adresse')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('logo', models.ImageField(blank=True, default='default.png', upload_to='vehicle_image')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisme',
                'verbose_name_plural': 'Organismes',
                'ordering': ('-createdAt',),
            },
        ),
    ]
