# Generated by Django 3.2.12 on 2022-04-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
