# Generated by Django 3.2.12 on 2022-05-14 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0003_affectation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectation',
            options={'ordering': ('-createdAt',), 'verbose_name': 'Affectation', 'verbose_name_plural': 'Affectations'},
        ),
    ]
