# Generated by Django 3.2.12 on 2022-04-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Intitulé')),
                ('email', models.CharField(blank=True, default='', max_length=100, verbose_name='Adresse email')),
                ('phone', models.CharField(blank=True, default='', max_length=100, verbose_name='Téléphone')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='Adresse')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prestataire',
                'verbose_name_plural': 'Prestataires',
                'ordering': ('-createdAt',),
            },
        ),
    ]
