# Generated by Django 3.2.12 on 2022-05-26 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_insurance_insuranceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasSupplier',
            fields=[
                ('provider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='provider.provider')),
            ],
            options={
                'verbose_name': 'Distributeur Carburant',
                'verbose_name_plural': 'Distributeurs Carburant',
                'ordering': ('-createdAt',),
            },
            bases=('provider.provider',),
        ),
        migrations.AlterModelOptions(
            name='insuranceprovider',
            options={'ordering': ('-createdAt',), 'verbose_name': 'Assureur', 'verbose_name_plural': 'Assureurs'},
        ),
        migrations.AlterField(
            model_name='insurance',
            name='endDate',
            field=models.DateField(blank=True, verbose_name='Date expiration'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='startDate',
            field=models.DateField(blank=True, verbose_name='Date début'),
        ),
    ]
