# Generated by Django 3.2.12 on 2022-05-28 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20220526_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('provider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='provider.provider')),
            ],
            options={
                'verbose_name': 'Prestataire de services',
                'verbose_name_plural': 'Prestataires de services',
                'ordering': ('-createdAt',),
            },
            bases=('provider.provider',),
        ),
        migrations.AlterModelOptions(
            name='gassupplier',
            options={'ordering': ('-createdAt',), 'verbose_name': 'Distributeur carburant', 'verbose_name_plural': 'Distributeurs carburant'},
        ),
        migrations.AddField(
            model_name='provider',
            name='rib',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='R.I.B'),
        ),
    ]
