# Generated by Django 3.2.12 on 2022-05-28 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20220526_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gassupplier',
            options={'ordering': ('-createdAt',), 'verbose_name': 'Distributeur carburant', 'verbose_name_plural': 'Distributeurs carburant'},
        )
    ]
