# Generated by Django 3.2.12 on 2022-05-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20220528_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('provider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='provider.provider')),
            ],
            options={
                'verbose_name': 'Prestataire de services',
                'verbose_name_plural': 'Prestataires de services',
                'ordering': ('-createdAt',),
            },
            bases=('provider.provider',),
        ),
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='id',
        ),
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='name',
        ),
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='provider_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='provider.provider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='rib',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='R.I.B'),
        ),
    ]
