# Generated by Django 3.2.12 on 2023-05-07 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Intitulé')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parc',
                'verbose_name_plural': 'Parcs',
                'ordering': ('-createdAt',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Dacia', max_length=50, verbose_name='Marque')),
                ('model', models.CharField(default='Logan', max_length=50, verbose_name='Modèle')),
                ('registration_plate', models.CharField(default='', max_length=200, verbose_name='Matricule')),
                ('vehicle_status', models.CharField(choices=[('B', 'En mission'), ('NB', 'Dans le parc'), ('NB', 'En panne'), ('R', 'En réparation'), ('A', 'Autre')], default='NB', max_length=2, verbose_name='État du véhicule')),
                ('insurance_status', models.CharField(choices=[('U', 'A jour'), ('NU', 'Hors échéance')], default='U', max_length=2, verbose_name='Assurance')),
                ('fuel_type', models.CharField(choices=[('D', 'Diesel'), ('G', 'Essence'), ('E', 'Eléctrique'), ('H', 'Hybride')], default='P', max_length=1, verbose_name='Type carburant')),
                ('mileage', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, verbose_name='Compteur')),
                ('vehicle_type', models.CharField(choices=[('P', 'Utilitaire'), ('T', 'Luxe'), ('C', 'Poids lourd'), ('G', 'Agricole'), ('M', 'Autre')], default='P', max_length=1, verbose_name='Type de véhicule')),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='vehicle_image')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('parking', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.parking', verbose_name='Parc')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ('-createdAt',),
            },
        ),
    ]
