# Generated by Django 3.2.12 on 2022-05-13 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        ('budget', '0008_delete_acquittance'),
        ('organism', '0003_affectation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(default=None, verbose_name='Numéro de décharge')),
                ('beneficiary', models.CharField(default='', max_length=200, verbose_name='Bénéficiaire')),
                ('assignedAt', models.DateField(default=None, verbose_name="Date d'attribution")),
                ('log_number', models.IntegerField(default=None, verbose_name='Numéro de carnet de bord')),
                ('amount', models.DecimalField(decimal_places=2, default=1000.0, max_digits=7, verbose_name='Montant')),
                ('observation', models.TextField(blank=True, default='', verbose_name='Observation')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('affectedTo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organism.affectation')),
                ('budget', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.budget')),
                ('vehicle', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Décharge',
                'verbose_name_plural': 'Décharges',
                'ordering': ('-createdAt',),
            },
        ),
    ]
