# Generated by Django 3.2.12 on 2022-05-13 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0003_affectation'),
        ('acquittance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquittance',
            name='affectedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organism.affectation', verbose_name='Affectation'),
        ),
    ]
