# Generated by Django 3.2.12 on 2022-05-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquittance', '0002_alter_acquittance_affectedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquittance',
            name='serial_number',
            field=models.PositiveIntegerField(default=None, verbose_name='Numéro de décharge'),
        ),
    ]
