# Generated by Django 3.2.12 on 2022-04-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0001_initial'),
        ('vehicle', '__first__'),
        ('budget', '0003_auto_20220402_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary', models.CharField(default='', max_length=200, verbose_name='Bénéficiaire')),
                ('description', models.TextField(default='', verbose_name='Mission')),
                ('appointment', models.DateField(default=None, verbose_name='Date de mission')),
                ('destination', models.CharField(default='', max_length=200, verbose_name='Destination')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('fuel', models.CharField(choices=[('D', 'Diesel'), ('G', 'Essence'), ('E', 'Eléctrique'), ('H', 'Hybride')], default='D', max_length=2, verbose_name='Type carburant')),
                ('observation', models.TextField(default='', verbose_name='Observation')),
                ('budget', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.budget', verbose_name='Budget')),
                ('district', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='district.district', verbose_name='Division')),
                ('vehicle', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle', verbose_name='Véhicule')),
            ],
        ),
    ]
