# Generated by Django 3.2.12 on 2022-04-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='voucher_number',
            field=models.CharField(default='', max_length=50, verbose_name='N° Bon'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='observation',
            field=models.TextField(blank=True, default='', verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, verbose_name='Quantité'),
        ),
    ]
