# Generated by Django 3.2.12 on 2022-04-03 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_auto_20220403_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ('-createdAt',), 'verbose_name': 'Mission', 'verbose_name_plural': 'Missions'},
        ),
        migrations.AddField(
            model_name='mission',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
