# Generated by Django 3.2.12 on 2022-04-05 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0001_initial'),
        ('mission', '0003_auto_20220403_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='organism',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organism.organism', verbose_name='Service'),
        ),
    ]
