# Generated by Django 3.2.12 on 2022-04-10 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_acquittance_assignedat'),
        ('mission', '0004_mission_organism'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='acquittance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='acquittance.acquittance', verbose_name='Décharge'),
        ),
    ]
