# Generated by Django 3.2.12 on 2022-04-10 02:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0005_mission_acquittance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='departure_time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 10, 2, 12, 8, 815334, tzinfo=utc), verbose_name='Heure départ'),
            preserve_default=False,
        ),
    ]
