# Generated by Django 3.2.12 on 2022-04-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0006_mission_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='departure_time',
            field=models.TimeField(blank=True, verbose_name='Heure départ'),
        ),
    ]
