# Generated by Django 3.2.12 on 2022-04-10 02:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0007_alter_mission_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='return_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 10, 2, 38, 47, 981380, tzinfo=utc), verbose_name='Heure retour'),
            preserve_default=False,
        ),
    ]
