# Generated by Django 3.2.12 on 2022-04-12 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
        ('mission', '0008_mission_return_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='provider',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='provider.provider', verbose_name='Prestataire'),
            preserve_default=False,
        ),
    ]
