# Generated by Django 3.2.12 on 2022-05-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0009_mission_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='acquittance',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='organism',
        ),
        migrations.AlterField(
            model_name='mission',
            name='voucher_number',
            field=models.PositiveIntegerField(default=0, max_length=50, verbose_name='N° Bon'),
        ),
    ]
