# Generated by Django 3.2.12 on 2022-05-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0010_auto_20220513_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Quantité'),
        ),
    ]
