# Generated by Django 3.2.12 on 2022-05-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0012_auto_20220513_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='voucher_number',
            field=models.CharField(default='', max_length=50, verbose_name='N° Bon'),
        ),
    ]
